import { createServer } from "node:http";
import { randomUUID } from "node:crypto";

const port = Number(process.env.PORT || 8787);
const sessions = new Map();

function json(res, statusCode, payload) {
  res.writeHead(statusCode, { "Content-Type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(payload));
}

function createHomeScreen() {
  return {
    id: "remote-home",
    title: "unstable-ui",
    subtitle: "Remote harness demo",
    blocks: [
      {
        id: "intro",
        type: "text",
        value: "This screen is being streamed from the demo harness server."
      },
      {
        id: "card-1",
        type: "card",
        title: "Current mode",
        body: "Remote harness over HTTP + SSE."
      },
      {
        id: "actions-1",
        type: "actions",
        items: [
          { id: "show-plan", label: "Show sample plan" },
          { id: "preview-asset", label: "Preview asset" },
          { id: "request-microphone", label: "Request microphone" }
        ]
      }
    ]
  };
}

function createPlanScreen() {
  return {
    id: "remote-plan",
    title: "Generated task plan",
    subtitle: "Returned by the remote harness",
    blocks: [
      {
        id: "list-1",
        type: "list",
        items: [
          { id: "a", title: "Capture voice input", description: "Submit transcript or audio context." },
          { id: "b", title: "Plan next actions", description: "Turn intent into a constrained workspace." },
          { id: "c", title: "Return structured UI", description: "Update the screen through schema events." }
        ]
      },
      {
        id: "actions-2",
        type: "actions",
        items: [
          { id: "preview-asset", label: "Preview asset" },
          { id: "back-home", label: "Back home" }
        ]
      }
    ]
  };
}

function createArtifactScreen() {
  return {
    id: "remote-artifact",
    title: "Artifact preview",
    subtitle: "Resource block sent by the remote harness",
    blocks: [
      {
        id: "resource-1",
        type: "resource",
        resource: {
          id: "artifact-1",
          kind: "link",
          uri: "https://github.com",
          source: "remote",
          title: "GitHub",
          previewable: true,
          openable: true
        }
      },
      {
        id: "actions-3",
        type: "actions",
        items: [{ id: "back-home", label: "Back home" }]
      }
    ]
  };
}

function createVoiceResultScreen(transcript) {
  return {
    id: "remote-voice-result",
    title: "Voice task result",
    subtitle: "Generated by the remote harness from voice.input",
    blocks: [
      {
        id: "voice-intro",
        type: "text",
        value: `Received voice input: "${transcript}"`
      },
      {
        id: "voice-card",
        type: "card",
        title: "Interpreted request",
        body: "The remote harness converted the voice input into a task-specific workspace."
      },
      {
        id: "voice-list",
        type: "list",
        items: [
          { id: "voice-step-1", title: "Capture intent", description: "The client sent a structured voice.input event." },
          { id: "voice-step-2", title: "Plan the next screen", description: "The server switched into thinking mode." },
          { id: "voice-step-3", title: "Wait for follow-up", description: "The runtime is ready for another event." }
        ]
      },
      {
        id: "voice-actions",
        type: "actions",
        items: [
          { id: "preview-asset", label: "Show linked artifact" },
          { id: "back-home", label: "Back home" }
        ]
      }
    ]
  };
}

function createCapabilityResultScreen(requestId, granted) {
  return {
    id: "remote-capability-result",
    title: "Capability result",
    subtitle: "Returned after capability.resolved",
    blocks: [
      {
        id: "capability-text",
        type: "text",
        value: `Capability request ${requestId} resolved with granted=${String(granted)}.`
      },
      {
        id: "capability-actions",
        type: "actions",
        items: [{ id: "back-home", label: "Back home" }]
      }
    ]
  };
}

function readJson(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];

    req.on("data", (chunk) => {
      chunks.push(chunk);
    });

    req.on("end", () => {
      if (chunks.length === 0) {
        resolve({});
        return;
      }

      try {
        resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")));
      } catch (error) {
        reject(error);
      }
    });

    req.on("error", reject);
  });
}

function writeEvent(res, event) {
  res.write(`data: ${JSON.stringify(event)}\n\n`);
}

function ensureSession(sessionId) {
  return sessions.get(sessionId);
}

function broadcast(sessionId, event) {
  const session = ensureSession(sessionId);

  if (!session) {
    return;
  }

  session.lastEvent = event;

  for (const client of session.clients) {
    writeEvent(client, event);
  }
}

function createSession() {
  const sessionId = randomUUID();
  sessions.set(sessionId, {
    clients: new Set(),
    screen: createHomeScreen(),
    status: "waiting"
  });
  return sessionId;
}

async function handleClientEvent(sessionId, event) {
  const session = ensureSession(sessionId);

  if (!session) {
    return;
  }

  if (event.type === "voice.input") {
    session.status = "thinking";
    session.screen = createVoiceResultScreen(event.transcript || "No transcript");
    broadcast(sessionId, { type: "status", phase: "thinking" });
    broadcast(sessionId, { type: "screen.updated", screen: session.screen });
    session.status = "waiting";
    broadcast(sessionId, { type: "status", phase: "waiting" });
    return;
  }

  if (event.type === "artifact.requested") {
    broadcast(sessionId, {
      type: "artifact.available",
      artifact: {
        id: event.artifactId,
        kind: "link",
        uri: "https://github.com",
        source: "remote",
        title: "GitHub",
        previewable: true,
        openable: true
      }
    });
    return;
  }

  if (event.type === "capability.resolved") {
    session.screen = createCapabilityResultScreen(event.requestId, event.payload?.granted);
    broadcast(sessionId, { type: "screen.updated", screen: session.screen });
    return;
  }

  if (event.type !== "action.triggered") {
    return;
  }

  if (event.actionId === "show-plan") {
    session.status = "thinking";
    session.screen = createPlanScreen();
    broadcast(sessionId, { type: "status", phase: "thinking" });
    broadcast(sessionId, { type: "screen.updated", screen: session.screen });
    session.status = "waiting";
    broadcast(sessionId, { type: "status", phase: "waiting" });
    return;
  }

  if (event.actionId === "preview-asset") {
    session.screen = createArtifactScreen();
    broadcast(sessionId, { type: "screen.updated", screen: session.screen });
    return;
  }

  if (event.actionId === "request-microphone") {
    broadcast(sessionId, {
      type: "capability.requested",
      request: {
        id: "cap_microphone_remote_demo",
        capability: "microphone",
        reason: "The remote harness wants to demonstrate the capability bridge flow."
      }
    });
    return;
  }

  if (event.actionId === "back-home") {
    session.screen = createHomeScreen();
    session.status = "waiting";
    broadcast(sessionId, { type: "screen.updated", screen: session.screen });
    broadcast(sessionId, { type: "status", phase: "waiting" });
  }
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url || "/", `http://${req.headers.host || "127.0.0.1"}`);
  const pathParts = url.pathname.split("/").filter(Boolean);

  if (req.method === "GET" && url.pathname === "/health") {
    json(res, 200, { ok: true });
    return;
  }

  if (req.method === "POST" && url.pathname === "/session/start") {
    const sessionId = createSession();
    json(res, 200, {
      sessionId,
      streamUrl: `/session/${sessionId}/stream`,
      eventUrl: `/session/${sessionId}/event`
    });
    return;
  }

  if (pathParts[0] === "session" && pathParts[2] === "stream" && req.method === "GET") {
    const sessionId = pathParts[1];
    const session = ensureSession(sessionId);

    if (!session) {
      json(res, 404, { error: "Session not found." });
      return;
    }

    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      "Access-Control-Allow-Origin": "*"
    });

    session.clients.add(res);
    writeEvent(res, { type: "session.started", sessionId });
    writeEvent(res, { type: "status", phase: session.status });
    writeEvent(res, { type: "screen.updated", screen: session.screen });

    req.on("close", () => {
      session.clients.delete(res);
      res.end();
    });
    return;
  }

  if (pathParts[0] === "session" && pathParts[2] === "event" && req.method === "POST") {
    const sessionId = pathParts[1];
    const session = ensureSession(sessionId);

    if (!session) {
      json(res, 404, { error: "Session not found." });
      return;
    }

    try {
      const event = await readJson(req);
      await handleClientEvent(sessionId, event);
      json(res, 202, { accepted: true });
    } catch (error) {
      json(res, 400, {
        error: error instanceof Error ? error.message : "Invalid JSON payload."
      });
    }
    return;
  }

  json(res, 404, { error: "Not found." });
});

server.listen(port, () => {
  console.log(`demo-harness listening on http://127.0.0.1:${port}`);
});
